import {fixture,validateCase,runWorkflow,approveHandoff,getRunLog} from './runtime.js';
export const STORAGE_KEY='airradius-public-fictional-v1';
export function parseImport(raw){if(typeof raw!=='string'||new TextEncoder().encode(raw).length>65536)throw new Error('Import exceeds 64 KB');const c=JSON.parse(raw);validateCase(c);return c;}
export function recordAction(c,type,text,assignee='demo-operator'){validateCase(c);if(!['NOTE','ASSIGN','CLOSE','REOPEN'].includes(type))throw new Error('Unknown action');if(typeof text!=='string'||!text.trim()||text.length>1000)throw new Error('A bounded note is required');if(type==='CLOSE'&&c.state==='CLOSED')throw new Error('Case already closed');if(type==='REOPEN'&&c.state!=='CLOSED')throw new Error('Only a closed case can reopen');if(!['demo-operator','shift-lead'].includes(assignee))throw new Error('Unknown fictional assignee');const next=structuredClone(c);next.version++;if(type==='CLOSE')next.state='CLOSED';if(type==='REOPEN')next.state='REOPENED';next.actions.push({id:`action-${next.version}`,type,at:new Date().toISOString(),actor:'demo-operator',text:type==='ASSIGN'?`Fictional assignee label ${assignee}: ${text.trim()}`:text.trim(),evidenceRefs:[`case:${c.id}`]});validateCase(next);return next;}
if(typeof document!=='undefined'){
 const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let current=fixture(),result=null,controller=null,consoleName='MOC',replay=false;
 const consoles={AIR:'Illustrative aircraft observations; identity remains unknown.',RF:'No RF feed configured. Missing data is unknown, not evidence of a clear area.',GEO:'Exercise coordinates only; no surveyed accuracy or live basemap.',INTEL:'No external intelligence source connected. No hostile intent established.',MOC:'Common picture of fictional observations and human exercise actions.',ADAPTERS:'No live adapters connected. Source names are synthetic fixture labels.',HISTORY:'Time-ordered observations and recorded actions; browser-local audit only.'};
 function notify(t){$('#notice').textContent=t;}function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(current));}catch{notify('Browser storage unavailable; export before leaving.');}}
 try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)current=parseImport(raw);}catch{notify('Saved exercise failed validation; using the fictional fixture.');}
 $('#tabs').innerHTML=Object.keys(consoles).map(n=>`<button data-console="${n}" aria-pressed="${n==='MOC'}">${n}</button>`).join('');
 function render(){const latest=Math.max(...current.observations.map(o=>Date.parse(o.observedAt)));$('#console-title').textContent=consoleName==='MOC'?'Common operational picture':consoleName;$('#console-detail').textContent=consoles[consoleName];$('#case-state').textContent=`${current.dataMode} · ${current.state} · Version ${current.version} · Exercise owner ${current.owner??'unassigned'}`;$('#evidence').innerHTML=current.observations.map(o=>`<div class="evidence-row"><strong>${esc(o.id)} · ${esc(o.source)}</strong><br>Evidence: observation:${esc(o.id)}<br>Observed ${esc(o.observedAt)}<br>Ingested ${esc(o.ingestedAt)}<br>${latest-Date.parse(o.observedAt)>60000?'STALE relative to exercise clock':'Within 60 seconds of exercise clock'} · ${Date.parse(o.ingestedAt)-Date.parse(o.observedAt)>5000?'DELAYED INGESTION':'Nominal fixture ingestion'} · Identity UNKNOWN</div>`).join('');$('#tracks').innerHTML=current.observations.map((o,i)=>`<circle cx="${200+Math.max(-140,Math.min(140,o.x*2))}" cy="${150-Math.max(-130,Math.min(130,o.y*2))}" r="6"/><text x="${210+Math.max(-140,Math.min(140,o.x*2))}" y="${150-Math.max(-130,Math.min(130,o.y*2))+i*15}">${esc(o.id)}</text>`).join('');$('#cursor').max=current.actions.length; if(!replay)$('#cursor').value=current.actions.length;renderHistory();$('#audit').textContent=JSON.stringify(getRunLog(),null,2);}
 function renderHistory(){const count=Number($('#cursor').value);$('#replay-state').textContent=replay?`REPLAY · ${count} of ${current.actions.length} actions · read-only history view`:'SIMULATED · current action history';$('#history').innerHTML=current.actions.slice(0,count).map(a=>`<li><strong>${esc(a.type)}</strong> · ${esc(a.at)}<br>${esc(a.text)}<br>action:${esc(a.id)} · ${esc(a.evidenceRefs.join(', '))}</li>`).join('');}
 $('#tabs').addEventListener('click',e=>{const b=e.target.closest('[data-console]');if(!b)return;consoleName=b.dataset.console;document.querySelectorAll('[data-console]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();});
 $('#cursor').addEventListener('input',()=>{replay=Number($('#cursor').value)<current.actions.length;renderHistory();});
 $('#action-form').addEventListener('submit',e=>{e.preventDefault();try{if(replay)throw new Error('Return history slider to current before editing');current=recordAction(current,e.submitter.value,$('#note').value,$('#assignee').value);persist();render();notify('Recorded in this fictional browser-local exercise.');}catch(err){notify(err.message);}});
 function renderResult(){if(!result)return;$('#result').innerHTML=`<p>${esc(result.status)} · ${esc(result.executionKind)} · ${esc(result.dataMode)} · ${esc(result.runId)}</p>${result.error?`<p>${esc(result.error.code)}: ${esc(result.error.message)}</p>`:''}<h3>Evidence-backed output</h3>${[...result.facts,...result.inferences,...result.recommendations].map(f=>`<p>${esc(f.text)}<br><small>${esc(f.evidenceRefs.join(', '))}</small></p>`).join('')}<h3>Limitations</h3><ul>${result.limitations.map(l=>`<li>${esc(l)}</li>`).join('')}</ul><p>Provider/model: none · Token usage/cost: unknown / not reported</p>`;$('#approve').hidden=!(result.agentId==='operator-handoff-coordinator'&&result.status==='SUCCEEDED');}
 async function execute(role,c=current){if(controller)return;controller=new AbortController();$('#cancel').disabled=false;$('#approve').hidden=true;try{result=await runWorkflow(role,c,{actor:'demo-operator',signal:controller.signal,timeoutMs:1000,onState:r=>{$('#run-state').textContent=`${r.status} · ${r.runId}`;}});renderResult();render();}catch(err){notify(err.message);}finally{controller=null;$('#cancel').disabled=true;}}
 document.querySelectorAll('[data-role]').forEach(b=>b.addEventListener('click',()=>execute(b.dataset.role)));$('#cancel').addEventListener('click',()=>controller?.abort());$('#failure').addEventListener('click',()=>execute('event-correlator',{...current,fictional:false}));
 $('#approve').addEventListener('click',()=>{try{current=approveHandoff(current,result,'demo-operator',current.version);persist();$('#approve').hidden=true;render();notify('Human approved the fictional draft. No message sent or operational action performed.');}catch(err){notify(err.message);}});
 $('#reset').addEventListener('click',()=>{controller?.abort();current=fixture();replay=false;result=null;$('#result').replaceChildren();$('#approve').hidden=true;persist();render();notify('Fictional case reset. Session workflow audit retained.');});
 $('#import').addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>65536)throw new Error('Import exceeds 64 KB');current=parseImport(await f.text());replay=false;persist();render();notify('Validated fictional exercise imported.');}catch(err){notify(err.message);}finally{e.target.value='';}});
 $('#export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({case:current,runAudit:getRunLog(),notice:'Fictional browser-local SIMULATED/REPLAY exercise; no authenticated audit.'},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='airradius-fictional-exercise-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Export contains case and audit. Import accepts the case object only, as documented.');});render();
}
