// Decorative motion only. Local preference is the sole stored value.
const root=document.documentElement,preference=matchMedia('(prefers-reduced-motion: reduce)'),storageKey='airradius.motion.paused';let userPaused=false;try{userPaused=localStorage.getItem(storageKey)==='true';}catch{}
const legacy=document.querySelector('#motion-toggle');const toggle=legacy??document.createElement('button');toggle.dataset.motionToggle='';if(!legacy){toggle.type='button';toggle.className='motion-control';document.body.append(toggle);}else{toggle.classList.add('motion-control');document.body.append(toggle);document.querySelector('.visual-scene')?.classList.remove('motion-paused');}
const rail=document.createElement('div');rail.className='motion-controls';rail.setAttribute('role','group');rail.setAttribute('aria-label','Display preferences');toggle.classList.remove('scene-control');rail.append(toggle);const header=document.querySelector('body>header');if(header)header.after(rail);else document.body.prepend(rail);
const atmosphere=document.createElement('div');atmosphere.className='motion-atmosphere';atmosphere.setAttribute('aria-hidden','true');document.body.prepend(atmosphere);
const host=document.querySelector('.vision-hero,.hero,.visual-scene');if(host){host.classList.add('motion-host');const cinema=document.createElement('div');cinema.className='motion-cinema';cinema.setAttribute('aria-hidden','true');host.prepend(cinema);}
function apply(){const reduced=preference.matches,hidden=document.hidden,paused=userPaused||hidden;root.dataset.motion=reduced?'reduced':paused?'paused':'running';toggle.disabled=reduced;toggle.setAttribute('aria-pressed',String(reduced||userPaused));toggle.textContent=reduced?'Reduced motion':userPaused?'Resume motion':'Pause motion';toggle.setAttribute('aria-label',reduced?'Motion reduced by your system preference':userPaused?'Resume decorative motion':'Pause decorative motion');toggle.toggleAttribute('data-hidden-pause',hidden);document.querySelector('.visual-scene')?.classList.toggle('motion-paused',reduced||paused);document.dispatchEvent(new CustomEvent('airradius-motion-change',{detail:{state:root.dataset.motion,userPaused,reduced}}));}
toggle.addEventListener('click',()=>{if(preference.matches){apply();return;}userPaused=!userPaused;try{localStorage.setItem(storageKey,String(userPaused));}catch{}apply();});preference.addEventListener('change',apply);document.addEventListener('visibilitychange',apply);window.addEventListener('storage',event=>{if(event.key===storageKey){userPaused=event.newValue==='true';apply();}});apply();
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const item of entries){if(item.isIntersecting){if(root.dataset.motion==='running')item.target.classList.add('motion-reveal');observer.unobserve(item.target);}}},{threshold:.12});document.querySelectorAll('main>section:not(.hero):not(.vision-hero),.detail-grid article,.use-card,.connection-card,.discovery,.pilot-shell>section,.panel').forEach(element=>observer.observe(element));}
