import test from 'node:test';
import assert from 'node:assert/strict';
import {proposePilot,validateInputs,proposalText} from '../js/pilot.js';
const team={organization:'venue',teamSize:'1-5',workspaces:1,priority:'handoff'};
test('pilot is a nonbinding planning draft with resolvable selection evidence and no submission',()=>{const before=JSON.stringify(team),p=proposePilot(team);assert.equal(p.binding,false);assert.equal(p.submissionState,'NOT_SUBMITTED');assert.equal(p.dataMode,'PLANNING');assert.equal(p.executionKind,'DETERMINISTIC');assert.equal(p.pilot.priceUsd,2500);assert.equal(p.pilot.durationDays,30);assert.equal(p.futurePlan.indicativeMonthlyUsd,750);assert.deepEqual(p.audit.map(a=>a.state),['QUEUED','RUNNING','SUCCEEDED']);for(const ref of p.evidenceRefs.filter(r=>r.startsWith('input:')))assert.ok(Object.hasOwn(p.inputs,ref.slice(6)));assert.equal(JSON.stringify(team),before);});
test('Operator and Partner proposed scope rules do not imply unlimited service',()=>{assert.equal(proposePilot({...team,teamSize:'6-20'}).futurePlan.indicativeMonthlyUsd,2500);const p=proposePilot({...team,organization:'partner',workspaces:12});assert.equal(p.futurePlan.indicativeMonthlyUsd,7750);assert.equal(p.futurePlan.extraWorkspaces,2);assert.equal(p.futurePlan.humanReviewRequired,true);assert.equal(proposePilot({...team,teamSize:'21+'}).futurePlan.name,'Partner');assert.equal(proposePilot({...team,workspaces:50}).futurePlan.indicativeMonthlyUsd,12500);});
test('untrusted personal and operational fields and invalid selector/range inputs rejected',()=>{for(const update of [{email:'unknown@example.test'},{records:[]},{workspaces:0},{workspaces:51},{workspaces:1.5},{workspaces:'2'},{organization:'<script>'},{teamSize:'1000'},{priority:'LIVE'}])assert.throws(()=>validateInputs({...team,...update}));assert.throws(()=>validateInputs(null));});
test('downloaded human-readable draft retains limitations, pricing version and evidence',()=>{const p=proposePilot(team),text=proposalText(p);assert.match(text,/NOT_SUBMITTED/);assert.match(text,/NONBINDING/);assert.ok(text.includes(p.rateVersion));assert.ok(text.includes(p.runId));assert.ok(text.includes('input:workspaces'));assert.match(text,/human scope approval required/);});
test('each actual invocation has a distinct run ID and complete local audit',()=>{const a=proposePilot(team),b=proposePilot(team);assert.notEqual(a.runId,b.runId);assert.equal(a.runState,'SUCCEEDED');assert.ok(Number.isFinite(Date.parse(a.finishedAt)));assert.equal(a.audit.length,3);});
