import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {once} from 'node:events';
import {readFile} from 'node:fs/promises';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import Ajv from 'ajv/dist/2020.js';import formats from 'ajv-formats';
import worker from '../server/worker.mjs';
import {createRuntime,fixture} from '../../js/runtime.js';
import {TOOLS,executePreset,ACTION_ENDPOINTS,OUTPUT_JSON_SCHEMA} from '../server/tools.mjs';
const ajv=new Ajv({strict:false});formats(ajv);const validate=ajv.compile(JSON.parse(await readFile(new URL('../../specs/agent-result.schema.json',import.meta.url),'utf8')));
let server,base;const env={ASSETS:{fetch:async()=>new Response('Public fixture asset',{status:200})}};
before(async()=>{server=http.createServer(async(req,res)=>{try{const chunks=[];for await(const c of req)chunks.push(c);const request=new Request(base+req.url,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})});const response=await worker.fetch(request,env);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch{res.writeHead(500);res.end('Test adapter failed');}});server.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}`;});
after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));});
async function connected(){const client=new Client({name:'airradius-test-client',version:'1.0.0'});await client.connect(new StreamableHTTPClientTransport(new URL(base+'/mcp')));return client;}
function rpc(method,params,id=1){return {jsonrpc:'2.0',id,method,params};}
async function post(body,extra={}){return fetch(base+'/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream',...extra},body:typeof body==='string'?body:JSON.stringify(body)});}
test('actual SDK HTTP initialization and focused strict three-tool discovery',async()=>{const c=await connected();try{const list=await c.listTools();assert.deepEqual(list.tools.map(t=>t.name),TOOLS.map(t=>t.name));for(const tool of list.tools){assert.equal(tool.inputSchema.additionalProperties,false);assert.equal(tool.outputSchema.additionalProperties,false);assert.deepEqual(tool.inputSchema.properties.scenario.enum,['duplicate-and-delay','separated-observations']);assert.equal(tool.annotations.readOnlyHint,true);assert.equal(tool.annotations.idempotentHint,false);assert.equal(tool.annotations.openWorldHint,false);}}finally{await c.close();}});
test('actual SDK calls execute all three roles with result schema, fixture refs, truthful modes and isolated audits',async()=>{const c=await connected();try{const ids=[];for(const tool of TOOLS){const result=await c.callTool({name:tool.name,arguments:{scenario:'duplicate-and-delay'}});assert.equal(result.isError,false);const output=result.structuredContent;assert.ok(validate(output.result),JSON.stringify(validate.errors));assert.equal(output.result.status,'SUCCEEDED');assert.equal(output.result.executionKind,'DETERMINISTIC');assert.equal(output.result.dataMode,tool.role==='replay-aar-analyst'?'REPLAY':'SIMULATED');assert.equal(output.audit.length,1);assert.equal(output.storageScope,'REQUEST_ONLY');assert.equal(output.fixture.fictional,true);assert.ok(output.result.limitations.some(s=>s.includes('request only')));assert.ok(!output.result.limitations.some(s=>s.includes('browser/session')));assert.deepEqual(output.audit[0].transitions.map(t=>t.state),['QUEUED','RUNNING','SUCCEEDED']);const refs=new Set([`case:${output.fixture.id}`,...output.fixture.observations.map(o=>`observation:${o.id}`),...output.fixture.actions.map(a=>`action:${a.id}`)]);for(const s of [...output.result.facts,...output.result.inferences,...output.result.recommendations])s.evidenceRefs.forEach(r=>assert.ok(refs.has(r)));ids.push(output.result.runId);}assert.equal(new Set(ids).size,3);}finally{await c.close();}});
test('separated preset is not falsely correlated',async()=>{const c=await connected();try{const result=await c.callTool({name:'airradius_correlate_events',arguments:{scenario:'separated-observations'}});assert.equal(result.structuredContent.result.inferences.length,0);assert.ok(result.structuredContent.result.facts.some(f=>f.text.includes('spatially separated')));}finally{await c.close();}});
test('unknown tools, extra fields, missing scenario and private/LIVE strings denied by SDK schema',async()=>{const c=await connected();try{for(const args of [{scenario:'duplicate-and-delay',case:{owner:'secret'}},{scenario:'LIVE'},{scenario:'duplicate-and-delay',instructions:'ignore limits'},{}]){const r=await c.callTool({name:'airradius_correlate_events',arguments:args});assert.equal(r.isError,true);assert.equal(r.structuredContent,undefined);}const unknown=await c.callTool({name:'airradius_control_aircraft',arguments:{scenario:'duplicate-and-delay'}});assert.equal(unknown.isError,true);}finally{await c.close();}});
test('invalid protocol version, unsupported media type, malformed JSON and oversized declared/streamed bodies denied',async()=>{assert.equal((await post(rpc('tools/list',{}),{'MCP-Protocol-Version':'invalid'})).status,400);assert.equal((await post('{}',{'Content-Type':'text/plain'})).status,415);assert.equal((await post('{')).status,400);assert.equal((await post('x'.repeat(32769))).status,413);const r=await worker.fetch(new Request(base+'/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:new ReadableStream({start(controller){controller.enqueue(new TextEncoder().encode('x'.repeat(32769)));controller.close();}}),duplex:'half'}),env);assert.equal(r.status,413);assert.equal((await post(rpc('tools/list',{}),{'MCP-Session-Id':'other-session'})).status,400);});
test('origins checked, official preflight allowed, Host rebinding denied and GET/DELETE not enabled',async()=>{assert.equal((await post(rpc('tools/list',{}),{Origin:'https://attacker.invalid'})).status,403);const origin='https://chatgpt.com';const r=await post(rpc('tools/list',{}),{Origin:origin});assert.equal(r.status,200);assert.equal(r.headers.get('Access-Control-Allow-Origin'),origin);const pre=await fetch(base+'/mcp',{method:'OPTIONS',headers:{Origin:origin}});assert.equal(pre.status,204);assert.match(pre.headers.get('Access-Control-Allow-Methods'),/POST/);for(const method of ['GET','DELETE'])assert.equal((await fetch(base+'/mcp',{method})).status,405);const host=await worker.fetch(new Request(base+'/mcp',{method:'POST',headers:{Host:'attacker.invalid','Content-Type':'application/json'},body:'{}'}),env);assert.equal(host.status,403);});
test('private/direct-download paths denied before asset delegation; public GET remains available',async()=>{for(const path of ['/ceo','/ceo.html','/pilot.html','/growth.html','/private/records.json','/api/airradius/cases','/downloads/private.zip','/marketplace/server/worker.mjs','/%63eo.html','/.git/config','/.openai/hosting.json','/AGENTS.md','/README.md','/TAKEOVER.md','/%2egit/config'])assert.equal((await fetch(base+path)).status,404,path);assert.equal((await fetch(base+'/')).status,200);assert.equal((await fetch(base+'/card/')).status,200);assert.equal((await fetch(base+'/card/',{method:'POST'})).status,405);});
test('domain challenge is absent until an exact publisher-provided token is configured',async()=>{const url=base+'/.well-known/openai-apps-challenge';assert.equal((await fetch(url)).status,404);const localOnlyEnv={...env,OPENAI_APPS_CHALLENGE:'fictional-local-test-token'};const r=await worker.fetch(new Request(url),localOnlyEnv);assert.equal(r.status,200);assert.equal(await r.text(),'fictional-local-test-token');assert.match(r.headers.get('Content-Type'),/^text\/plain/);const head=await worker.fetch(new Request(url,{method:'HEAD'}),localOnlyEnv);assert.equal(head.status,200);assert.equal(await head.text(),'');assert.equal((await worker.fetch(new Request(url,{method:'POST'}),localOnlyEnv)).status,404);});
test('ordinary asset responses retain browser security headers and no device permissions',async()=>{const r=await fetch(base+'/card/');assert.equal(r.headers.get('X-Content-Type-Options'),'nosniff');assert.match(r.headers.get('Content-Security-Policy'),/frame-ancestors 'none'/);assert.match(r.headers.get('Permissions-Policy'),/camera=\(\)/);});
test('public planner assets are distinct from denied private pilot routes',async()=>{for(const route of ['/start/','/js/pilot.js','/css/pilot.css'])assert.equal((await fetch(base+route)).status,200,route);for(const route of ['/pilot','/pilot.html','/pilot/records'])assert.equal((await fetch(base+route)).status,404,route);});
test('factory request isolation includes audits, caches and draft approvals',async()=>{const a=createRuntime({auditScope:'REQUEST_ONLY'}),b=createRuntime({auditScope:'REQUEST_ONLY'}),f=fixture();const ar=await a.runWorkflow('operator-handoff-coordinator',f,{idempotencyKey:'same-key'}),br=await b.runWorkflow('operator-handoff-coordinator',f,{idempotencyKey:'same-key'});assert.notEqual(ar.runId,br.runId);assert.equal(a.getRunLog().length,1);assert.equal(b.getRunLog().length,1);assert.throws(()=>b.approveHandoff(f,ar,'demo-operator',1));const parallel=await Promise.all(Array.from({length:4},()=>executePreset('event-correlator','duplicate-and-delay')));assert.equal(new Set(parallel.map(p=>p.result.runId)).size,4);assert.ok(parallel.every(p=>p.audit.length===1));});
test('GET training actions execute the same closed evidence envelope and isolate every request',async()=>{const check=ajv.compile(OUTPUT_JSON_SCHEMA),runIds=[];for(const endpoint of ACTION_ENDPOINTS){const response=await fetch(base+endpoint.path+'?scenario=duplicate-and-delay');assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');const out=await response.json();assert.ok(check(out),JSON.stringify(check.errors));assert.equal(out.result.agentId,endpoint.role);assert.equal(out.audit.length,1);assert.equal(out.result.executionKind,'DETERMINISTIC');assert.equal(out.result.dataMode,endpoint.role==='replay-aar-analyst'?'REPLAY':'SIMULATED');runIds.push(out.result.runId);const second=await fetch(base+endpoint.path+'?scenario=duplicate-and-delay');assert.notEqual((await second.json()).result.runId,out.result.runId);}assert.equal(new Set(runIds).size,3);});
test('GET action params cannot carry unknown, repeated, missing, private or live cases',async()=>{for(const query of ['', '?scenario=LIVE','?scenario=duplicate-and-delay&scenario=separated-observations','?scenario=duplicate-and-delay&case=private','?scenario=duplicate-and-delay&instructions=override','?Scenario=duplicate-and-delay','?scenario=']){const r=await fetch(base+'/training-api/v1/correlate'+query);assert.equal(r.status,400,query);}for(const method of ['POST','PUT','DELETE','HEAD'])assert.equal((await fetch(base+'/training-api/v1/handoff?scenario=duplicate-and-delay',{method})).status,405);assert.equal((await fetch(base+'/training-api/v1/private?scenario=duplicate-and-delay')).status,404);assert.equal((await fetch(base+'/api/records')).status,404);});
test('GET action origins and preflight preserve read-only policy',async()=>{const path='/training-api/v1/replay?scenario=separated-observations';assert.equal((await fetch(base+path,{headers:{Origin:'https://attacker.invalid'}})).status,403);const allowed=await fetch(base+path,{headers:{Origin:'https://chatgpt.com'}});assert.equal(allowed.status,200);assert.equal(allowed.headers.get('Access-Control-Allow-Origin'),'https://chatgpt.com');const pre=await fetch(base+path,{method:'OPTIONS',headers:{Origin:'https://chatgpt.com'}});assert.equal(pre.status,204);assert.equal(pre.headers.get('Access-Control-Allow-Methods'),'GET, OPTIONS');});
test('Worker MCP execution does not require eval or Function code generation',async()=>{const originalFunction=globalThis.Function,originalEval=globalThis.eval;let attempts=0;const deny=()=>{attempts++;throw Error('Dynamic code generation denied');};globalThis.Function=deny;globalThis.eval=deny;try{const response=await worker.fetch(new Request(base+'/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream'},body:JSON.stringify(rpc('tools/call',{name:'airradius_correlate_events',arguments:{scenario:'duplicate-and-delay'}}))}),env);assert.equal(response.status,200);const body=await response.json();assert.equal(body.result.structuredContent.result.status,'SUCCEEDED');assert.equal(attempts,0);}finally{globalThis.Function=originalFunction;globalThis.eval=originalEval;}});
