import {mkdir,writeFile} from 'node:fs/promises';
import {ACTION_ENDPOINTS,OUTPUT_JSON_SCHEMA,SCENARIOS} from '../marketplace/server/tools.mjs';
const base='https://airradius.kaij4u.chatgpt.site',dir='marketplace/gpt-store';await mkdir(dir,{recursive:true});
function clean(value){if(Array.isArray(value))return value.map(clean);if(value&&typeof value==='object'){const result={};for(const[k,v]of Object.entries(value)){if(['$schema','$id','$defs'].includes(k))continue;result[k]=k==='$ref'&&v.startsWith('#/$defs/')?v.replace('#/$defs/','#/components/schemas/AirRadius_'):clean(v);}return result;}return value;}
const schemas={TrainingOutput:clean(OUTPUT_JSON_SCHEMA),Error:{type:'object',required:['error'],additionalProperties:false,properties:{error:{type:'string'}}}};
for(const[name,schema]of Object.entries(OUTPUT_JSON_SCHEMA.$defs??{}))schemas[`AirRadius_${name}`]=clean(schema);
const descriptions=['Analyze a selected built-in fictional scenario for duplicate candidates, delayed ingestion and proximity hypotheses. Results are SIMULATED deterministic drafts with evidence and an audit. No live data or private records.','Draft a briefing from a selected built-in fictional case. Returns a SIMULATED deterministic training draft with evidence and limitations. Does not send, approve or assign a handoff.','Reconstruct a selected fictional observation/action timeline. Returns a REPLAY deterministic after-action draft with evidence, uncertainty and request audit. No live sensing or operational control.'];
const paths={};for(const[e,i]of ACTION_ENDPOINTS.map((e,i)=>[e,i]))paths[e.path]={get:{operationId:e.operationId,summary:e.title,description:descriptions[i],'x-openai-isConsequential':false,security:[],parameters:[{name:'scenario',in:'query',required:true,description:'Select a built-in fictional training preset. Do not send case data, private records, personal information or credentials.',schema:{type:'string',enum:SCENARIOS}}],responses:{'200':{description:'Executed fictional workflow, full source evidence and request-only audit.',content:{'application/json':{schema:{$ref:'#/components/schemas/TrainingOutput'}}}},'400':{description:'Unsupported, repeated, missing or extra input.',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}},'500':{description:'Execution failed; do not invent a successful result.',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}}}}};
const spec={openapi:'3.1.0',info:{title:'AirRadius Training Actions',version:'0.1.0',description:'Three read-only, preset-only fictional training workflows. No model calls, imports, private records or operational actions.',termsOfService:base+'/terms.html'},servers:[{url:base}],security:[],paths,components:{schemas}};
await writeFile(dir+'/openapi.json',JSON.stringify(spec,null,2)+'\n');
await writeFile(dir+'/builder-config.json',JSON.stringify({name:'AirRadius Training',description:'Practice fictional event correlation, handoff drafting and replay review with evidence, clear data modes and an audit.',conversationStarters:['Correlate the duplicate-and-delay fictional scenario.','Draft a handoff for the separated-observations training case.','Analyze the duplicate-and-delay replay.'],instructionsFile:'instructions.md',knowledgeFiles:['training-handbook.md'],icon:'../plugin/assets/logo.png',actionsSchema:'openapi.json',actionAuthentication:'None — built-in public fictional presets only',privacyPolicyURL:base+'/privacy.html',capabilities:{webSearch:false,imageGeneration:false,codeInterpreter:false},creationStatus:'NOT_CREATED',publishingStatus:'NOT_SUBMITTED',accountEligibility:'UNVERIFIED'},null,2)+'\n');
console.log('Generated GPT Builder configuration and three focused OpenAPI Actions. No GPT was created or published.');
